export enum Role {
    ROLE_PRODUCT_FIND_ALL = 'ROLE_PRODUCT_FIND_ALL',
    ROLE_PRODUCT_FIND = 'ROLE_PRODUCT_FIND',
    ROLE_PRODUCT_SAVE = 'ROLE_PRODUCT_SAVE',
    ROLE_PRODUCT_EDIT = 'ROLE_PRODUCT_EDIT',
    ROLE_PRODUCT_DELETE = 'ROLE_PRODUCT_DELETE',

    ROLE_CATEGORY_FIND_ALL = 'ROLE_CATEGORY_FIND_ALL',
    ROLE_CATEGORY_FIND = 'ROLE_CATEGORY_FIND',
    ROLE_CATEGORY_SAVE = 'ROLE_CATEGORY_SAVE',
    ROLE_CATEGORY_EDIT = 'ROLE_CATEGORY_EDIT',
    ROLE_CATEGORY_DELETE = 'ROLE_CATEGORY_DELETE',

    ROLE_ADDRESS_FIND_ALL = 'ROLE_ADDRESS_FIND_ALL',
    ROLE_ADDRESS_FIND = 'ROLE_ADDRESS_FIND',
    ROLE_ADDRESS_SAVE = 'ROLE_ADDRESS_SAVE',
    ROLE_ADDRESS_EDIT = 'ROLE_ADDRESS_EDIT',
    ROLE_ADDRESS_DELETE = 'ROLE_ADDRESS_DELETE',

    ROLE_USER_FIND_ALL = 'ROLE_USER_FIND_ALL',
    ROLE_USER_FIND = 'ROLE_USER_FIND',
    ROLE_USER_SAVE = 'ROLE_USER_SAVE',
    ROLE_USER_EDIT = 'ROLE_USER_EDIT',
    ROLE_USER_DELETE = 'ROLE_USER_DELETE',

    ROLE_USER_COMPANY_FIND_ALL = 'ROLE_USER_COMPANY_FIND_ALL',
    ROLE_USER_COMPANY_ID_COMPANY_FIND_ALL = 'ROLE_USER_COMPANY_ID_COMPANY_FIND_ALL',
    ROLE_USER_COMPANY_FIND = 'ROLE_USER_COMPANY_FIND',
    ROLE_USER_COMPANY_SAVE = 'ROLE_USER_COMPANY_SAVE',
    ROLE_USER_COMPANY_EDIT = 'ROLE_USER_COMPANY_EDIT',
    ROLE_USER_COMPANY_DELETE = 'ROLE_USER_COMPANY_DELETE',
    ROLE_USER_COMPANY_PASSWORD_EDIT = 'ROLE_USER_COMPANY_PASSWORD_EDIT',

    ROLE_USER_CLIENT_FIND_ALL = 'ROLE_USER_CLIENT_FIND_ALL',
    ROLE_USER_CLIENT_FIND = 'ROLE_USER_CLIENT_FIND',
    ROLE_USER_CLIENT_SAVE = 'ROLE_USER_CLIENT_SAVE',
    ROLE_USER_CLIENT_EDIT = 'ROLE_USER_CLIENT_EDIT',
    ROLE_USER_CLIENT_DELETE = 'ROLE_USER_CLIENT_DELETE',

    ROLE_COMPANY_FIND_ALL = 'ROLE_COMPANY_FIND_ALL',
    ROLE_COMPANY_FIND = 'ROLE_COMPANY_FIND',
    ROLE_COMPANY_SAVE = 'ROLE_COMPANY_SAVE',
    ROLE_COMPANY_EDIT = 'ROLE_COMPANY_EDIT',
    ROLE_COMPANY_DELETE = 'ROLE_COMPANY_DELETE',

    ROLE_PARENT_COMPANY_FIND_ALL = 'ROLE_PARENT_COMPANY_FIND_ALL',
    ROLE_PARENT_COMPANY_FIND = 'ROLE_PARENT_COMPANY_FIND',
    ROLE_PARENT_COMPANY_SAVE = 'ROLE_PARENT_COMPANY_SAVE',
    ROLE_PARENT_COMPANY_EDIT = 'ROLE_PARENT_COMPANY_EDIT',
    ROLE_PARENT_COMPANY_DELETE = 'ROLE_PARENT_COMPANY_DELETE',

    ROLE_EXTRA_FIND_ALL = 'ROLE_EXTRA_FIND_ALL',
    ROLE_EXTRA_FIND = 'ROLE_EXTRA_FIND',
    ROLE_EXTRA_SAVE = 'ROLE_EXTRA_SAVE',
    ROLE_EXTRA_EDIT = 'ROLE_EXTRA_EDIT',
    ROLE_EXTRA_DELETE = 'ROLE_EXTRA_DELETE',

    ROLE_PREFERENCE_FIND_ALL = 'ROLE_PREFERENCE_FIND_ALL',
    ROLE_PREFERENCE_FIND = 'ROLE_PREFERENCE_FIND',
    ROLE_PREFERENCE_SAVE = 'ROLE_PREFERENCE_SAVE',
    ROLE_PREFERENCE_EDIT = 'ROLE_PREFERENCE_EDIT',
    ROLE_PREFERENCE_DELETE = 'ROLE_PREFERENCE_DELETE',

    ROLE_OPENING_HOURS_FIND_ALL  = 'ROLE_OPENING_HOURS_FIND_ALL',
    ROLE_OPENING_HOURS_EDIT = 'ROLE_OPENING_HOURS_EDIT',

    ROLE_DELIVERY_FEES_FIND_ALL = 'ROLE_DELIVERY_FEES_FIND_ALL',
    ROLE_DELIVERY_FEES_SAVE = 'ROLE_DELIVERY_FEES_SAVE',
    ROLE_DELIVERY_FEES_EDIT = 'ROLE_DELIVERY_FEES_EDIT',

    ROLE_SALES_FIND_ALL = 'ROLE_SALES_FIND_ALL',

    ROLE_SALES_SETTINGS_FIND_ONE = 'ROLE_SALES_SETTINGS_FIND_ONE'
}
